name: Nightly Scrape

on:
  schedule:
    - cron: '0 0 * * *'   # kjører hver dag kl 00:00 UTC
  workflow_dispatch:       # lar deg trigge jobben manuelt fra GitHub UI
permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: python scorpion_scraper/nightly_scrape.py
      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "Update scraped data" || echo "No changes to commit"
          git push
